# Default values for node-red.
replicaCount: 1

image:
  repository: nodered/node-red-docker
  tag: v8
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  # We don't need no basic authentication here, this is handled by node-red's settings
  annotations: {}
  path: /
  hosts:
    - node-red.local

settings:
  uiHost: ""
  httpAdminRoot: "/admin"
  httpNodeRoot: "/nodes"
  uiRoot: "ui"
  auth:
    adminUser: "admin"
    adminPassHash: ""
  requireHttps: false
  logging:
    level: "warn"
    metrics: false
    audit: false
  projects:
    enabled: true
  credentialSecret: ""
  userDir: "/usr/src/node-red/config"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
