apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "node-red.fullname" . }}
  labels:
    app: {{ template "node-red.name" . }}
    chart: {{ template "node-red.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configuration.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "node-red.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "node-red.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.env }}
          env:
{{ toYaml .Values.env | indent 10}}
          {{- end -}}
          ports:
            - name: http
              containerPort: 1880
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /admin
              port: http
          readinessProbe:
            httpGet:
              path: /admin
              port: http
          volumeMounts:
          - mountPath: /data/settings.js
            name: config
            subPath: settings.js
      volumes:
      - name: config
        configMap:
          name: {{ template "node-red.fullname" . }}-settings
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
